# Generated by Django 5.1.11 on 2025-07-02 18:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('pars_date', models.DateTimeField(auto_now_add=True)),
                ('digest', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('site_url', models.URLField()),
                ('lang', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('en|ru|kk')])),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.base')),
                ('cr_site_url', models.URLField(max_length=2000)),
                ('isActive', models.BooleanField(default=True)),
            ],
            bases=('v1.base',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.base')),
                ('ev_site_url', models.URLField(max_length=2000)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
            bases=('v1.base',),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.base')),
                ('ar_date', models.DateTimeField(blank=True, null=True)),
                ('ar_site_url', models.URLField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'ordering': ['-ar_date'],
            },
            bases=('v1.base',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.base')),
                ('pr_site_url', models.URLField(max_length=2000)),
                ('isActive', models.BooleanField(default=True)),
            ],
            bases=('v1.base',),
        ),
    ]
