# Generated by Django 4.2.11 on 2026-06-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_subscriber_confirm_token_subscriber_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='genre_preferences',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
