from django.urls import path

from .admin_views import (
    AdminCommentViewSet,
    AdminContentSourcesView,
    AdminCourseViewSet,
    AdminDashboardView,
    AdminEventViewSet,
    AdminNewsViewSet,
    AdminProjectViewSet,
    AdminSubscriberViewSet,
    AdminUserViewSet,
)
from .views import (
    CommentViewSet,
    CourseViewSet,
    EventViewSet,
    NewsViewSet,
    ProjectViewSet,
    RunParsersView,
    SubscribeConfirmView,
    SubscribeView,
    getCourseSiteList,
    getEventSiteList,
    getNewsSiteList,
    getProjectSiteList,
)

urlpatterns = [
    path("Courses/", CourseViewSet.as_view({"get": "list", "post": "create"})),
    path("Courses/<int:pk>", CourseViewSet.as_view({"get": "retrieve", "put": "update", "patch": "partial_update", "delete": "destroy"})),
    path("Courses/Sites/", getCourseSiteList),
    path("News/", NewsViewSet.as_view({"get": "list", "post": "create"})),
    path("News/<int:pk>", NewsViewSet.as_view({"get": "retrieve", "put": "update", "patch": "partial_update", "delete": "destroy"})),
    path("News/Sites/", getNewsSiteList),
    path("Projects/", ProjectViewSet.as_view({"get": "list", "post": "create"})),
    path("Projects/<int:pk>", ProjectViewSet.as_view({"get": "retrieve", "put": "update", "patch": "partial_update", "delete": "destroy"})),
    path("Events/", EventViewSet.as_view({"get": "list", "post": "create"})),
    path("Events/<int:pk>", EventViewSet.as_view({"get": "retrieve", "put": "update", "patch": "partial_update", "delete": "destroy"})),
    path("Comments/", CommentViewSet.as_view({"get": "list", "post": "create"})),
    path("Comments/<int:pk>", CommentViewSet.as_view({"get": "retrieve", "put": "update", "patch": "partial_update", "delete": "destroy"})),
    path("subscribe/", SubscribeView.as_view(), name="subscribe"),
    path("subscribe/confirm/<uuid:token>/", SubscribeConfirmView.as_view(), name="subscribe-confirm"),
    path("admin/dashboard/", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("admin/sources/", AdminContentSourcesView.as_view(), name="admin-sources"),
    path("admin/users/", AdminUserViewSet.as_view({"get": "list"}), name="admin-users"),
    path("admin/users/<int:pk>/", AdminUserViewSet.as_view({"get": "retrieve", "patch": "partial_update", "put": "update", "delete": "destroy"}), name="admin-user-detail"),
    path("admin/subscribers/", AdminSubscriberViewSet.as_view({"get": "list"}), name="admin-subscribers"),
    path("admin/subscribers/<int:pk>/", AdminSubscriberViewSet.as_view({"get": "retrieve", "patch": "partial_update", "put": "update", "delete": "destroy"}), name="admin-subscriber-detail"),
    path("admin/comments/", AdminCommentViewSet.as_view({"get": "list"}), name="admin-comments"),
    path("admin/comments/<int:pk>/", AdminCommentViewSet.as_view({"get": "retrieve", "patch": "partial_update", "put": "update", "delete": "destroy"}), name="admin-comment-detail"),
    path("admin/courses/", AdminCourseViewSet.as_view({"get": "list", "post": "create"}), name="admin-courses"),
    path("admin/courses/<int:pk>/", AdminCourseViewSet.as_view({"get": "retrieve", "patch": "partial_update", "put": "update", "delete": "destroy"}), name="admin-course-detail"),
    path("admin/news/", AdminNewsViewSet.as_view({"get": "list", "post": "create"}), name="admin-news"),
    path("admin/news/<int:pk>/", AdminNewsViewSet.as_view({"get": "retrieve", "patch": "partial_update", "put": "update", "delete": "destroy"}), name="admin-news-detail"),
    path("admin/projects/", AdminProjectViewSet.as_view({"get": "list", "post": "create"}), name="admin-projects"),
    path("admin/projects/<int:pk>/", AdminProjectViewSet.as_view({"get": "retrieve", "patch": "partial_update", "put": "update", "delete": "destroy"}), name="admin-project-detail"),
    path("admin/events/", AdminEventViewSet.as_view({"get": "list", "post": "create"}), name="admin-events"),
    path("admin/events/<int:pk>/", AdminEventViewSet.as_view({"get": "retrieve", "patch": "partial_update", "put": "update", "delete": "destroy"}), name="admin-event-detail"),
    path("parsers/run/", RunParsersView.as_view(), name="run-parsers"),
]
