# Generated by Django 5.0.7 on 2024-07-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
