# Generated by Django 5.0.7 on 2024-07-19 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_course_isactive_project_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.base')),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('isActive', models.BooleanField()),
            ],
            bases=('v1.base',),
        ),
    ]
