# Generated by Django 5.0.7 on 2024-07-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_alter_base_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
