# Generated by Django 5.0.7 on 2024-07-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_event_event_site_url_alter_course_cr_site_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_site_url',
            new_name='ev_site_url',
        ),
    ]
