# Generated by Django 5.0.7 on 2024-08-11 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0012_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='lang',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('en|ru|kz')]),
        ),
    ]
