# Generated by Django 5.0.7 on 2024-10-31 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0015_ourarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourarticle',
            name='lang',
        ),
    ]
