# Generated by Django 5.0.7 on 2024-10-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0016_remove_ourarticle_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='OurArticleId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
