# Generated by Django 5.0.7 on 2024-10-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0017_article_ourarticleid'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='HasOurArticle',
            field=models.BooleanField(default=False),
        ),
    ]
