# Generated by Django 5.0.7 on 2024-10-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0018_article_hasourarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourarticle',
            name='Engtext',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='ourarticle',
            name='Engtitle',
            field=models.TextField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='ourarticle',
            name='Kktext',
            field=models.TextField(blank=True, default='Жок', null=True),
        ),
        migrations.AlterField(
            model_name='ourarticle',
            name='Kktitle',
            field=models.TextField(blank=True, default='Жок', null=True),
        ),
    ]
