# Generated by Django 5.0.7 on 2024-11-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0020_oururls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oururls',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
