# Generated by Django 5.0.7 on 2024-11-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0021_alter_oururls_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oururls',
            name='title',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
