# Generated by Django 3.2.12 on 2024-07-16 04:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('pars_date', models.DateTimeField(auto_now_add=True)),
                ('digest', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('site_url', models.URLField()),
                ('lang', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[a-z]*$')])),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.base')),
                ('ar_date', models.DateTimeField()),
                ('ar_site_url', models.URLField()),
            ],
            bases=('v1.base',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.base')),
                ('cr_site_url', models.URLField()),
            ],
            bases=('v1.base',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.base')),
                ('pr_site_url', models.URLField()),
            ],
            bases=('v1.base',),
        ),
    ]
