# Generated by Django 5.0.7 on 2024-07-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
