# Generated by Django 5.0.7 on 2024-07-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_alter_base_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ar_site_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='base',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
