# Generated by Django 5.0.7 on 2024-07-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_alter_article_ar_site_url_alter_base_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_site_url',
            field=models.URLField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='cr_site_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='project',
            name='pr_site_url',
            field=models.URLField(max_length=2000),
        ),
    ]
