# Generated by Django 5.0.7 on 2024-07-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0008_rename_event_site_url_event_ev_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
