# Generated by Django 5.0.7 on 2024-07-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_alter_event_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ar_site_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
