# Generated by Django 5.0.7 on 2024-08-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0010_alter_article_ar_site_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-ar_date']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_start_date']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='event_end_date',
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
