# Generated by Django 5.0.7 on 2024-08-06 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0011_alter_article_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_end_date',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_start_date',
        ),
    ]
