# Generated by Django 5.0.7 on 2024-08-11 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0013_alter_base_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='lang',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('en|ru|kk')]),
        ),
    ]
