# Generated by Django 5.0.7 on 2024-10-31 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0014_alter_base_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rutitle', models.TextField()),
                ('Engtitle', models.TextField(blank=True, null=True)),
                ('Kktitle', models.TextField(blank=True, null=True)),
                ('Rutext', models.TextField()),
                ('Engtext', models.TextField(blank=True, null=True)),
                ('Kktext', models.TextField(blank=True, null=True)),
                ('lang', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('en|ru|kk')])),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
