# Generated by Django 5.0.7 on 2024-11-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0019_alter_ourarticle_engtext_alter_ourarticle_engtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(editable=False, max_length=255)),
                ('url', models.URLField()),
            ],
        ),
    ]
