# Generated by Django 5.0.7 on 2024-11-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0023_alter_oururls_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurUrls',
            new_name='OurUrl',
        ),
    ]
