# Generated by Django 5.0.7 on 2024-11-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0024_rename_oururls_oururl'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ourarticle',
            name='Engtext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ourarticle',
            name='Engtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ourarticle',
            name='Kktext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ourarticle',
            name='Kktitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ourarticle',
            name='Rutitle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
