# Generated by Django 5.0.7 on 2024-11-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0025_ourevent_alter_ourarticle_engtext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rutitle', models.TextField()),
                ('Engtitle', models.TextField(blank=True, null=True)),
                ('Kktitle', models.TextField(blank=True, null=True)),
                ('Rutext', models.TextField()),
                ('Engtext', models.TextField(blank=True, null=True)),
                ('Kktext', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OurArticle',
        ),
        migrations.DeleteModel(
            name='OurEvent',
        ),
    ]
