# Generated by Django 5.0.7 on 2024-11-12 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0026_ourbase_delete_ourarticle_delete_ourevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurArticle',
            fields=[
                ('ourbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.ourbase')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('v1.ourbase',),
        ),
        migrations.CreateModel(
            name='OurCourse',
            fields=[
                ('ourbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.ourbase')),
                ('duration', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('instructor', models.CharField(max_length=255)),
                ('is_online', models.BooleanField(default=False)),
            ],
            bases=('v1.ourbase',),
        ),
        migrations.CreateModel(
            name='OurEvent',
            fields=[
                ('ourbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.ourbase')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=('v1.ourbase',),
        ),
        migrations.CreateModel(
            name='OurProject',
            fields=[
                ('ourbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.ourbase')),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('v1.ourbase',),
        ),
    ]
