# Generated by Django 5.0.7 on 2024-11-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0027_ourarticle_ourcourse_ourevent_ourproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='HasOurCourse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='OurCourseId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='HasOurEvent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='OurEventId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='HasOurProject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='OurProjectId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
