# Generated by Django 5.0.7 on 2025-01-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0028_course_hasourcourse_course_ourcourseid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourcourse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
