# Generated by Django 5.0.7 on 2025-01-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0029_ourcourse_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourevent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
