# Generated by Django 5.0.7 on 2025-01-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0030_ourevent_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourproject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
