# Generated by Django 5.0.7 on 2025-01-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0031_ourproject_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourcourse',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ourproject',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('planned', 'Planned'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
    ]
