# Generated by Django 5.0.7 on 2025-01-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0032_alter_ourcourse_duration_alter_ourproject_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourcourse',
            name='duration',
            field=models.FloatField(),
        ),
    ]
