# Generated by Django 5.0.7 on 2025-01-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0033_alter_ourcourse_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourcourse',
            name='duration',
            field=models.IntegerField(verbose_name='Duration in hours'),
        ),
    ]
