# Generated by Django 5.0.7 on 2025-01-14 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0036_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ourevent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ourproject',
            name='created_at',
        ),
        migrations.AddField(
            model_name='ourbase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourbase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
