# Generated by Django 5.0.7 on 2025-01-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0037_remove_ourevent_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/ourarticles/'),
        ),
        migrations.AddField(
            model_name='ourcourse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/ourcourses/'),
        ),
        migrations.AddField(
            model_name='ourevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/ourevents/'),
        ),
        migrations.AddField(
            model_name='ourproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/ourprojects/'),
        ),
    ]
