# Generated by Django 5.0.7 on 2025-03-17 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0038_ourarticle_image_ourcourse_image_ourevent_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleToFilter',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.article')),
                ('esgScore', models.IntegerField()),
            ],
            bases=('v1.article',),
        ),
        migrations.AddField(
            model_name='article',
            name='Approved',
            field=models.BooleanField(default=True),
        ),
    ]
