# Generated by Django 5.0.7 on 2025-03-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0039_articletofilter_article_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParsedSite', models.URLField()),
                ('ErrorText', models.TextField()),
                ('ErrorDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='articletofilter',
            options={'ordering': ['esgScore']},
        ),
    ]
