# Generated by Django 5.0.7 on 2025-03-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0040_parsingerror_alter_articletofilter_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Approved',
        ),
        migrations.AddField(
            model_name='base',
            name='Approved',
            field=models.BooleanField(default=True),
        ),
    ]
