# Generated by Django 5.0.7 on 2025-03-22 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0041_remove_article_approved_base_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseToFilter',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.course')),
                ('esgScore', models.IntegerField()),
            ],
            options={
                'ordering': ['esgScore'],
                'abstract': False,
            },
            bases=('v1.course', models.Model),
        ),
        migrations.CreateModel(
            name='EventToFilter',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.event')),
                ('esgScore', models.IntegerField()),
            ],
            options={
                'ordering': ['esgScore'],
                'abstract': False,
            },
            bases=('v1.event', models.Model),
        ),
        migrations.CreateModel(
            name='ProjectToFilter',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='v1.project')),
                ('esgScore', models.IntegerField()),
            ],
            options={
                'ordering': ['esgScore'],
                'abstract': False,
            },
            bases=('v1.project', models.Model),
        ),
    ]
