# Generated by Django 5.0.7 on 2025-03-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0042_coursetofilter_eventtofilter_projecttofilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('TelegramID', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
