# Generated by Django 5.0.7 on 2025-04-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0043_telegramuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='blacklistLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
    ]
