# Generated by Django 5.0.7 on 2025-05-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0044_blacklistlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
